package dev.ibrahims.sdwebuiapi

data class ADetailer(
    val model: String,
    val prompt: String,
    val negativePrompt: String,
    val confidence: Float = 0.3f,
    val maskKLargest: Float = 0.0f,
    val maskMinRatio: Float = 0.0f,
    val maskMaxRatio: Float = 1.0f,
    val dilateErode: Int = 4,
    val xOffset: Int = 0,
    val yOffset: Int = 0,
    val maskMergeInvert: String? = null,
    val maskBlur: Int = 4,
    val denoisingStrength: Float = 0.4f,
    val inpaintOnlyMasked: Boolean = true,
    val inpaintOnlyMaskedPadding: Int = 32,
    val useInpaintWidthHeight: Boolean = false,
    val inpaintWidth: Int = 512,
    val inpaintHeight: Int = 512,
    val useSteps: Boolean = false,
    val steps: Int = 28,
    val useCfgScale: Boolean = false,
    val cfgScale: Float = 7.0f,
    val useNoiseMultiplier: Boolean = false,
    val noiseMultiplier: Float = 1.0f,
    val useClipSkip: Boolean = false,
    val clipSkip: Int = 1,
    val restoreFace: Boolean = false,
    val controlNetModel: String? = null,
    val controlNetModule: String? = null,
    val controlNetWeight: Float = 1.0f,
    val controlNetGuidanceStart: Float = 0.0f,
    val controlNetGuidanceEnd: Float = 1.0f
)
