package dev.ibrahims.sdwebui.payload

import dev.ibrahims.sdwebui.payload.script.ScriptPayload
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Image2ImagePayload(
    @SerialName("init_images") val initImages: List<String>,
    @SerialName("prompt") val prompt: String,
    @SerialName("negative_prompt") val negativePrompt: String,
    @SerialName("resize_mode") val resizeMode: Int,
    @SerialName("denoising_strength") val denoisingStrength: Float,
    @SerialName("mask") val mask: String?,
    @SerialName("mask_blur") val maskBlur: Int,
    @SerialName("inpainting_fill") val inpaintingFill: Int,
    @SerialName("inpaint_full_res") val inpaintFullRes: Boolean,
    @SerialName("inpaint_full_res_padding") val inpaintFullResPadding: Int,
    @SerialName("inpainting_mask_invert") val inpaintingMaskInvert: Int,
    @SerialName("initial_noise_multiplier") val initialNoiseMultiplier: Int,
    @SerialName("styles") val styles: List<String>,
    @SerialName("seed") val seed: Int,
    @SerialName("subseed") val subseed: Int,
    @SerialName("subseed_strength") val subseedStrength: Int,
    @SerialName("seed_resize_from_h") val seedResizeFromH: Int,
    @SerialName("seed_resize_from_w") val seedResizeFromW: Int,
    @SerialName("batch_size") val batchSize: Int,
    @SerialName("n_iter") val nIter: Int,
    @SerialName("steps") val steps: Int,
    @SerialName("cfg_scale") val cfgScale: Float,
    @SerialName("image_cfg_scale") val imageCfgScale: Float,
    @SerialName("width") val width: Int,
    @SerialName("height") val height: Int,
    @SerialName("restore_faces") val restoreFaces: Boolean,
    @SerialName("tiling") val tiling: Boolean,
    @SerialName("do_not_save_samples") val doNotSaveSamples: Boolean,
    @SerialName("eta") val eta: Float,
    @SerialName("s_churn") val sChurn: Int,
    @SerialName("s_tmax") val sTmax: Int,
    @SerialName("s_tmin") val sTmin: Int,
    @SerialName("s_noise") val sNoise: Int,
    @SerialName("override_settings") val overrideSettings: Map<String, String>,
    @SerialName("override_settings_restore_afterwards") val overrideSettingsRestoreAfterwards: Boolean,
    @SerialName("sampler_name") val samplerName: String,
    @SerialName("sampler_index") val samplerIndex: String,
    @SerialName("include_init_images") val includeInitImages: Boolean,
    @SerialName("script_name") val scriptName: String?,
    @SerialName("script_args") val scriptArgs: List<String>,
    @SerialName("send_images") val sendImages: Boolean,
    @SerialName("save_images") val saveImages: Boolean,
    @SerialName("alwayson_scripts") val alwaysonScripts: Map<String, ScriptPayload>,
)
